# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-27 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailling_start_at', models.DateTimeField(verbose_name='Mailing start')),
                ('mailling_end_at', models.DateTimeField(verbose_name='End of mailing')),
                ('tag', models.CharField(blank=True, max_length=30, verbose_name='Search by tag')),
                ('template_name', models.CharField(max_length=30, verbose_name='Template name')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now=True, verbose_name='Time of sending')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Time of create')),
                ('sending_status', models.CharField(choices=[('SENT', 'SENT'), ('NO_SENT', 'NO_SENT')], default='NO_SENT', max_length=10, verbose_name='Status of sending')),
                ('read_status', models.CharField(choices=[('READ', 'READ'), ('NOT_READ', 'NOT_READ')], default='NOT_READ', max_length=10, verbose_name='Status of reading')),
                ('mailing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.Mailing')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second name')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('tag', models.CharField(max_length=30, verbose_name='Search by tag')),
                ('subscriber_email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.Subscriber'),
        ),
    ]
