# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-28 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='mailling_end_at',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='tag',
            field=models.CharField(max_length=30, verbose_name='Tag for grouping'),
        ),
    ]
