# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-28 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20230128_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='subject',
            field=models.CharField(blank=True, max_length=50, verbose_name='Subject of the mailing'),
        ),
    ]
