# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-30 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_auto_20230130_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='tag',
        ),
    ]
