# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-09 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_auto_20230130_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='mailing',
            name='subscribers',
            field=models.ManyToManyField(db_table='mailing_subscribers', related_name='subscribers', to='mailing.Subscriber'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
